import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

const API='http://localhost:5140';
type User={id:string;username:string;displayName:string;role:string};
type Person={id:string;personCode:string;firstName:string;lastName:string;nationalId?:string|null;note?:string|null};
type Finger={id:string;fingerCode:string;position:string;sequenceNo:number;width:number;height:number;capturedAtUtc:string;syncStatus:string};
type RealtimeCapture={sessionId:string;width:number;height:number;pngBase64:string|null;status:'starting'|'inprogress'|'done'|'failed';hasImage:boolean;error?:string|null};
const fingers=['L1','L2','L3','L4','L5','R1','R2','R3','R4','R5'];
const fingerLabels:Record<string,string>={L1:'นิ้วโป้ง',L2:'นิ้วชี้',L3:'นิ้วกลาง',L4:'นิ้วนาง',L5:'นิ้วก้อย',R1:'นิ้วโป้ง',R2:'นิ้วชี้',R3:'นิ้วกลาง',R4:'นิ้วนาง',R5:'นิ้วก้อย'};
const pos=[['left','ซ้าย'],['center','กลาง'],['right','ขวา']] as const;
async function api(path:string,init:RequestInit={},token?:string){const headers=new Headers(init.headers);headers.set('Content-Type','application/json');if(token)headers.set('Authorization',`Bearer ${token}`);const res=await fetch(API+path,{...init,headers});if(!res.ok)throw new Error(`HTTP ${res.status}`);return res.status===204?null:res.json()}
function Login({onLogin}:{onLogin:(token:string,user:User)=>void}){const[u,setU]=useState('admin'),[p,setP]=useState('ChangeMe123!'),[err,setErr]=useState(''),[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setErr('');setBusy(true);try{const x=await api('/api/auth/login',{method:'POST',body:JSON.stringify({username:u,password:p})});onLogin(x.token,x.user)}catch{setErr('ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง')}finally{setBusy(false)}}return <div className="login"><form onSubmit={submit} className="card login-card"><h1>Fingerprint Collection</h1><p>ระบบเก็บลายนิ้วมือ Offline</p><label>ชื่อผู้ใช้<input value={u} onChange={e=>setU(e.target.value)}/></label><label>รหัสผ่าน<input type="password" value={p} onChange={e=>setP(e.target.value)}/></label>{err&&<div className="error">{err}</div>}<button disabled={busy}>{busy?'กำลังเข้าสู่ระบบ...':'Login'}</button><small>ทดสอบ: admin / ChangeMe123!</small></form></div>}
function App(){const[token,setToken]=useState(localStorage.getItem('of_token')||''),[user,setUser]=useState<User|null>(()=>{try{return JSON.parse(localStorage.getItem('of_user')||'null')}catch{return null}}),[persons,setPersons]=useState<Person[]>([]),[search,setSearch]=useState(''),[selected,setSelected]=useState<Person|null>(null),[finger,setFinger]=useState('L1'),[position,setPosition]=useState('center'),[images,setImages]=useState<Finger[]>([]),[preview,setPreview]=useState<string|null>(null),[pending,setPending]=useState<RealtimeCapture|null>(null),[err,setErr]=useState(''),[scanner,setScanner]=useState(false),[form,setForm]=useState({personCode:'',firstName:'',lastName:'',nationalId:'',note:''});
const pollTimer=useRef<number|undefined>(undefined);const liveCanvas=useRef<HTMLCanvasElement|null>(null);const imageCache=useRef<string>('');
function login(t:string,u:User){localStorage.setItem('of_token',t);localStorage.setItem('of_user',JSON.stringify(u));setToken(t);setUser(u)}
function logout(){localStorage.removeItem('of_token');localStorage.removeItem('of_user');setToken('');setUser(null)}
async function loadPersons(){try{const x=await api('/api/persons'+(search?`?search=${encodeURIComponent(search)}`:''),{},token);setPersons(x)}catch(e){setErr(String(e))}}
async function loadImages(personId:string){try{setImages(await api(`/api/fingerprints/person/${personId}`,{},token))}catch(e){setErr(String(e))}}
useEffect(()=>{if(token)loadPersons()},[token]);useEffect(()=>{if(selected)loadImages(selected.id);else setImages([])},[selected]);useEffect(()=>()=>{if(pollTimer.current)window.clearTimeout(pollTimer.current)},[]);
const current=useMemo(()=>images.filter(x=>x.fingerCode===finger&&x.position===position),[images,finger,position]);
useEffect(()=>{const p=pending;if(!p?.pngBase64||!liveCanvas.current||p.pngBase64===imageCache.current)return;imageCache.current=p.pngBase64;const canvas=liveCanvas.current;const img=new Image();img.onload=()=>{if(!liveCanvas.current)return;const ctx=canvas.getContext('2d');if(!ctx)return;if(canvas.width!==p.width||canvas.height!==p.height){canvas.width=p.width;canvas.height=p.height}ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height)};img.src=`data:image/png;base64,${p.pngBase64}`},[pending?.pngBase64,pending?.width,pending?.height]);
async function savePerson(e:React.FormEvent){e.preventDefault();try{const x=await api('/api/persons',{method:'POST',body:JSON.stringify(form)},token);setPersons(p=>[...p,x]);setForm({personCode:'',firstName:'',lastName:'',nationalId:'',note:''});setErr('เพิ่ม Person แล้ว')}catch(e){setErr(String(e))}}
async function pollRealtime(sessionId:string){try{const x=await api(`/api/capture/realtime/${sessionId}`,{},token) as RealtimeCapture;setPending(prev=>prev?.sessionId===sessionId?{...x}:prev);if(x.status==='inprogress'||x.status==='starting'){pollTimer.current=window.setTimeout(()=>pollRealtime(sessionId),250)}else{setScanner(false);if(x.status==='failed')setErr(x.error||'การสแกนลายนิ้วมือล้มเหลว')}}catch(e){setScanner(false);setErr(String(e))}}
async function capture(){if(!selected)return setErr('กรุณาเลือก Person ก่อน');if(scanner||pending)return;setErr('');imageCache.current='';setScanner(true);try{const x=await api('/api/capture/realtime/start',{method:'POST',body:JSON.stringify({personId:selected.id,fingerCode:finger,position})},token) as {sessionId:string,status:string};setPending({sessionId:x.sessionId,width:320,height:480,pngBase64:null,status:'starting',hasImage:false});pollRealtime(x.sessionId)}catch(e){setScanner(false);setErr(String(e))}}
async function cancelCapture(){if(!pending)return;const sessionId=pending.sessionId;try{await api(`/api/capture/realtime/${sessionId}/cancel`,{method:'POST'},token)}catch{}if(pollTimer.current)window.clearTimeout(pollTimer.current);setPending(null);setScanner(false);imageCache.current=''}
async function confirmCapture(){if(!selected||!pending||pending.status!=='done')return;setErr('');setScanner(true);try{await api(`/api/capture/realtime/${pending.sessionId}/confirm`,{method:'POST',body:JSON.stringify({personId:selected.id,fingerCode:finger,position})},token);setPending(null);await loadImages(selected.id);setErr('บันทึกลายนิ้วมือแล้ว')}catch(e){setErr(String(e))}finally{setScanner(false)}}
async function view(id:string){try{const r=await fetch(`${API}/api/fingerprints/${id}/preview`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error();setPreview(URL.createObjectURL(await r.blob()))}catch{setErr('เปิดภาพไม่ได้')}}
const countFor=(code:string,posi:string)=>images.filter(x=>x.fingerCode===code&&x.position===posi).length;
if(!token||!user)return <Login onLogin={login}/>;
const CapturePanel=()=>pending? <div className="capture-panel"><div className="capture-head"><div><div className="capture-title">SCANNING / CAPTURE</div><div className="capture-subtitle">{selected?.personCode} • {selected?.firstName} {selected?.lastName}</div></div><button className="icon-close" onClick={cancelCapture}>×</button></div><div className="capture-body"><div className="capture-preview-column"><div className="live-label">ภาพลายนิ้วมือแบบ Realtime</div><div className="live-frame stable"><canvas ref={liveCanvas} width={320} height={480} /></div><div className="live-meta">320 × 480 • 8-bit Grayscale</div></div><div className="capture-info-column"><div className="capture-current"><span className="eyebrow">กำลังเก็บ</span><strong>{finger} · {fingerLabels[finger]}</strong><span>ตำแหน่ง: {pos.find(x=>x[0]===position)?.[1]}</span></div><div className="legend"><span><i className="status-dot idle"/>ยังไม่ได้เก็บ</span><span><i className="status-dot scanning"/>กำลังสแกน</span><span><i className="status-dot saved"/>เก็บแล้ว</span></div><div className="hand-block"><h4>มือซ้าย</h4>{fingers.filter(x=>x.startsWith('L')).map(code=><div className="finger-row" key={code}><span className="finger-name"><b>{code}</b>{fingerLabels[code]}</span><div className="finger-pos-grid">{pos.map(([v,l])=><button key={v} className={`mini-pos ${finger===code&&position===v?'selected':''} ${countFor(code,v)>0?'saved':''}`} onClick={()=>{setFinger(code);setPosition(v)}}>{l}</button>)}</div></div>)}</div><div className="hand-block"><h4>มือขวา</h4>{fingers.filter(x=>x.startsWith('R')).map(code=><div className="finger-row" key={code}><span className="finger-name"><b>{code}</b>{fingerLabels[code]}</span><div className="finger-pos-grid">{pos.map(([v,l])=><button key={v} className={`mini-pos ${finger===code&&position===v?'selected':''} ${countFor(code,v)>0?'saved':''}`} onClick={()=>{setFinger(code);setPosition(v)}}>{l}</button>)}</div></div>)}</div></div></div><div className="capture-footer"><div className="capture-status"><i className={`status-dot ${pending.status==='done'?'saved':scanner?'scanning':'idle'}`}/>{pending.status==='done'?'จับภาพเสร็จแล้ว ตรวจสอบภาพก่อนบันทึก':scanner?'กำลังรับภาพจาก Futronic FS80H...':'พร้อมทำงาน'}</div><div className="capture-actions"><button className="secondary" onClick={cancelCapture}>ยกเลิก</button><button className="secondary" onClick={()=>{cancelCapture();setTimeout(capture,0)}} disabled={scanner}>↻ สแกนใหม่</button><button className="primary" onClick={confirmCapture} disabled={scanner||pending.status!=='done'}>✓ ยืนยันบันทึกภาพนี้</button></div></div></div>:null;
return <div className="app"><header><div><b>FINGERPRINT COLLECTION</b><span>พนักงาน: {user.displayName} ({user.role})</span></div><button className="ghost" onClick={logout}>ออกจากระบบ</button></header><main className="grid"><section className="card"><h2>Person</h2><div className="row"><input placeholder="ค้นหา Person..." value={search} onChange={e=>setSearch(e.target.value)}/><button onClick={loadPersons}>ค้นหา</button></div><div className="list">{persons.map(p=><button className={selected?.id===p.id?'item selected':'item'} key={p.id} onClick={()=>setSelected(p)}><b>{p.personCode}</b><span>{p.firstName} {p.lastName}</span></button>)}</div><h3>เพิ่ม Person</h3><form className="form" onSubmit={savePerson}><input placeholder="PersonCode" required value={form.personCode} onChange={e=>setForm({...form,personCode:e.target.value})}/><input placeholder="ชื่อ" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/><input placeholder="นามสกุล" value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/><input placeholder="เลขบัตร" value={form.nationalId} onChange={e=>setForm({...form,nationalId:e.target.value})}/><input placeholder="หมายเหตุ" value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/><button>เพิ่ม Person</button></form></section><section className="card"><h2>Fingerprint Capture</h2>{selected?<><div className="selected-person"><b>{selected.personCode}</b><span>{selected.firstName} {selected.lastName}</span></div><div className="hands"><div><h3>LEFT HAND</h3><div className="finger-grid">{fingers.filter(x=>x[0]==='L').map(f=><button className={finger===f?'chip active':'chip'} key={f} onClick={()=>setFinger(f)}>{f}</button>)}</div></div><div><h3>RIGHT HAND</h3><div className="finger-grid">{fingers.filter(x=>x[0]==='R').map(f=><button className={finger===f?'chip active':'chip'} key={f} onClick={()=>setFinger(f)}>{f}</button>)}</div></div></div><div className="positions">{pos.map(([v,l])=><button key={v} className={position===v?'pos active':'pos'} onClick={()=>setPosition(v)}>{l} <b>{images.filter(x=>x.fingerCode===finger&&x.position===v).length}</b></button>)}</div><div className="scanarea"><div className="scanner">Futronic FS80H<span className={scanner?'dot busy':'dot'}/></div><button className="scan" disabled={scanner||!!pending} onClick={capture}>{scanner?'กำลังสแกน...':pending?'ตรวจสอบภาพก่อนบันทึก':`Scan ${finger} • ${position}`}</button></div><h3>ภาพที่บันทึก</h3><div className="thumbs">{current.map(x=><button key={x.id} onClick={()=>view(x.id)}>✓ {x.sequenceNo}</button>)}</div></>:<div className="empty">เลือก Person ก่อน</div>}{err&&<div className="info">{err}</div>}</section></main>{CapturePanel()}{preview&&<div className="modal" onClick={()=>setPreview(null)}><div className="modalbox" onClick={e=>e.stopPropagation()}><img src={preview}/><button onClick={()=>setPreview(null)}>ปิด</button></div></div>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
